### ISSUE TITLE
iOS 10 changes - autodetection issues, orientation changes

### ISSUE THREAD

**Issue by xjki** [mmackh/IPDFCameraViewController#27] opened 2016-09-14 09:47 UTC
Seems that iOS10 brings some changes that makes library perform different than on iOS9/iOS8 - it seems harder for me to autodect correct frame on challenging light conditions, pictures taken in portrait are saved in landscape orientation.

**Comment by flashfabrixx** [comment] 2016-09-14 15:07
@xjki It seems like the coordination system changed in iOS 10. To fix that pictures take in portrait are saved in landscape orientation, I changed the [correctPerspectiveForImage:](https://github.com/mmackh/IPDFCameraViewController/blob/master/IPDFCameraViewController/IPDFCameraViewController.m#L458) method. 

``` objective-c
- (CIImage *)correctPerspectiveForImage:(CIImage *)image withFeatures:(CIRectangleFeature *)rectangleFeature
{  
    NSMutableDictionary *rectangleCoordinates = [NSMutableDictionary new];
    rectangleCoordinates[@"inputTopRight"] = [CIVector vectorWithCGPoint:rectangleFeature.topRight];
    rectangleCoordinates[@"inputBottomLeft"] = [CIVector vectorWithCGPoint:rectangleFeature.bottomLeft];
    
    // Fix landscape orientiation in iOS 10 by switching topLeft and bottomRight coordinates
    if ([[[UIDevice currentDevice] systemVersion] compare:@"10.0" options:NSNumericSearch] != NSOrderedAscending) {
        rectangleCoordinates[@"inputTopLeft"] = [CIVector vectorWithCGPoint:rectangleFeature.bottomRight];
        rectangleCoordinates[@"inputBottomRight"] = [CIVector vectorWithCGPoint:rectangleFeature.topLeft];
    } else {
        rectangleCoordinates[@"inputTopLeft"] = [CIVector vectorWithCGPoint:rectangleFeature.topLeft];
        rectangleCoordinates[@"inputBottomRight"] = [CIVector vectorWithCGPoint:rectangleFeature.bottomRight];
    }
    return [image imageByApplyingFilter:@"CIPerspectiveCorrection" withInputParameters:rectangleCoordinates];
}

**Comment by ddferrando** [comment] 2016-09-20 09:47
Hi @xjki.
I am making some test with your IPDFCameraViewController and it's really an amazing controller.
Regarding this change to work properly with iOs 10, I am having some strange issues.
In some cases, the image is rotated upside down. 180º.
I am trying to understand why it's having this behaviour but I can't not find the solution. 
Did you notice it?
Do you know any solution for this?
Thanks

**Comment by mmackh** [comment] 2016-09-20 11:43
Hi everyone. I've pushed a fix just now that fixes these orientation issues without checking what iOS version the device is on. It treats the cause more than the symptom in this case. Thanks for brining this to my attention.

**Closed by mmackh** 2016-09-20 11:43 UTC

**Comment by mattfxyz** [comment] 2016-12-06 00:33
Is this iOS 10 change documented anywhere? This problem has been driving me insane for a week now.
